server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springdatajdbc?serverTimezone=Europe/Moscow
    username: root
    password: sasha
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
      enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE